### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt4.QtWebKit'

### ISSUE THREAD

**Issue by mgundogdu1** [ciscorn/ldoce5viewer#48]
Thanks for this great application. 
After my last Manjaro installation I can't open the application.
Here is the output
Traceback (most recent call last):
  File "/usr/bin/ldoce5viewer", line 9, in <module>
    sys.exit(qtgui.run(sys.argv))
  File "/usr/lib/python3.6/site-packages/ldoce5viewer/qtgui/__init__.py", line 97, in run
    from .main import MainWindow
  File "/usr/lib/python3.6/site-packages/ldoce5viewer/qtgui/main.py", line 19, in <module>
    from PyQt4.QtWebKit import *
ModuleNotFoundError: No module named 'PyQt4.QtWebKit'

**Comment by gitfortat** [comment]
I have the same problem after upgrading my arch system. It's all over the place if you search for it. Seems like pyQt4 webkit bindings were removed from arch (and other distros?). How about a port to Qt5? Don't really understand how one can remove something that works just fine and is needed for other packages. Not really a problem with ldoce5viewer, though.

**Comment by elFua** [comment]
@mgundogdu1: There is in fact a version ported to Qt5 and it is available on Archlinux/Manjaro from AUR: `yaourt -S ldoce5viewer-pyqt5-git`, and it just works on my manjaro box. 

For other linuces this repo can be used: https://github.com/purboo/ldoce5viewer-pyqt5

**Comment by mgundogdu1** [comment]
Thank you @elFua . I have already installed ldoce5viewer-pyqt5-git 👍 It works perfect on Manjaro linux.
This problem solved thanks to https://aur.archlinux.org/packages/ldoce5viewer-pyqt5-git
