### ISSUE TITLE
arch linux build - no sound

### ISSUE THREAD

**Issue by arch1bald** [ciscorn/ldoce5viewer#6]
after building ldoceviewer-git there is no sound 

arch linux fully updated, all dependencies installed
sound is working in ldoceviewer 2013.04.24 build

to make sound work in git version it is enough to replace file ldoce5viewer-master/ldoce5viewer/qtgui/utils/soundplayer.py with file from previous version

Below, output of strace command after clicking on speaker icon in both versions

strace -e open ldoce5viewer

ldoceviewer 2013.04.24

open("/home/p/.local/share/ldoce5viewer/filemap.cdb", O_RDONLY) = 22
open("/home/p/Longman/LDOCE5/ldoce5.data/gb_hwd_pron.skn/files.skn/CONTENT.tda", O_RDONLY) = 22
open("/tmp/sbrj3w.tmp.mp3", O_RDWR|O_CREAT|O_EXCL|O_NOFOLLOW, 0600) = 22
open("/tmp/sbrj3w.tmp.mp3", O_RDONLY)   = 22
open("/tmp/sbrj3w.tmp.mp3", O_RDONLY)   = 22
open("/home/p/.pulse/client.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/p/.config/pulse/client.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/pulse/client.conf", O_RDONLY|O_CLOEXEC) = 24
open("/home/p/.config/pulse/cookie", O_RDONLY|O_NOCTTY|O_CLOEXEC) = 25
open("/home/p/.Xauthority", O_RDONLY)   = 25
open("/dev/shm/pulse-shm-3532668092", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 25
open("/dev/shm/pulse-shm-3972538594", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 25
open("/dev/shm/pulse-shm-2710348303", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 25
open("/dev/shm/pulse-shm-2396281625", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 25
open("/dev/shm/pulse-shm-2009650952", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 25
open("/dev/shm/pulse-shm-2672583405", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 25
open("/dev/urandom", O_RDONLY|O_NOCTTY|O_CLOEXEC) = 24
open("/dev/shm/pulse-shm-1516626791", O_RDWR|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC, 0700) = 24
open("/etc/machine-id", O_RDONLY|O_CLOEXEC) = 24
open("/tmp/sbrj3w.tmp.mp3", O_RDONLY)   = 25
open("/tmp/sbrj3w.tmp.mp3", O_RDONLY)   = 25
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 26

ldoceviewer git

open("/home/p/.local/share/ldoce5viewer/filemap.cdb", O_RDONLY) = 19
open("/home/p/Longman/LDOCE5/ldoce5.data/us_hwd_pron.skn/files.skn/CONTENT.tda", O_RDONLY) = 19

**Comment by bzhao** [comment]
I am Arch Linux user,  I haved tried to do everything from this site, but still do have sound
As per https://github.com/ciscorn/ldoce5viewer/issues/15, I install cheese package, the result is I have sound back. 
Thank all guys here!
